// productsDATA.js

const productsDATA = {
    products: [
      

    {
      id: 1,
      name: "Polo Ralph Lauren Island Fleece Long Sleeve Sweatshirt",
      price: 759.00,
      image: "https://img01.ztat.net/article/spp-media-p1/85da2d9b58694fda8ef2b3e330312400/d5886ef6e31346eb89e98657cb47ba5e.jpg?imwidth=1800",
      type: "clothing",
      description: "Stylowa bluza z kapturem w kolorze Alpine Blue, wykonana z miękkiej bawełny.",
      company: "Polo Ralph Lauren",
      color: "Blue",
      size: "S, M, L, XL",
      link: "https://www.zalando.pl/polo-ralph-lauren-island-fleece-long-sleeve-sweatshirt-bluza-z-kapturem-alpine-blue-po221j09u-k13.html",
      category: "men",
      style: "streetwear, casual"
    },
    {
      id: 2,
      name: "Tommy Hilfiger Hoodie Unisex",
      price: 280.00,
      image: "https://img01.ztat.net/article/spp-media-p1/4c86bdae52dd41db92bef770588e8a68/5ff0cc44163a41b394cc3d509290110b.jpg?imwidth=18000",
      type: "clothing",
      description: "Klasyczna biała bluza z kapturem i kieszenią typu kangur.",
      company: "Tommy Hilfiger",
      color: "White",
      size: "S, M, L, XL",
      link: "https://www.zalando.pl/tommy-hilfiger-hoodie-unisex-bluza-white-to1210049-a11.html",
      category: "unisex",
      style: "streetwear, casual"
    },
    {
      id: 3,
      name: "Jordan Jacket",
      price: 305.00,
      image: "https://img01.ztat.net/article/spp-media-p1/6e3a18c7656948d1970686a834b6719b/b645663ddd854e888ed81d6e09a817f8.jpg?imwidth=1800",
      type: "clothing",
      description: "Czarna bluza rozpinana z białymi detalami, idealna na co dzień.",
      company: "Jordan",
      color: "Black, White",
      size: "S, M, L, XL",
      link: "https://www.zalando.pl/jordan-bluza-rozpinana-blackwhite-joc21j022-q11.html",
      category: "men",
      style: "streetwear, casual"
    },
    {
      id: 4,
      name: "Levi's Denim Jacket",
      price: 89.99,
      image: "https://lsco.scene7.com/is/image/lsco/A48200016-dynamic1-pdp?fmt=jpeg&qlt=70&resMode=sharp2&fit=crop,1&op_usm=0.6,0.6,8&wid=1120&hei=1494",
      type: "clothing",
      description: "A classic Levi’s jacket for everyday wear.",
      company: "Levi's",
      color: "Blue",
      size: "S, M, L, XL",
      link: "",
      category: "men",
      style: "casual, streetwear"
    },
    {
      id: 5,
      name: "Adidas Originals Hoodie",
      price: 59.99,
      image: "https://i8.amplience.net/i/jpl/jd_729934_a?qlt=92",
      type: "clothing",
      description: "A cozy hoodie for everyday comfort with a sleek Adidas design.",
      company: "Adidas",
      color: "Black",
      size: "M, L, XL",
      link: "",
      category: "men",
      style: "streetwear, casual"
    },
    // Here we continue by filling in more product data for a total of 50...
    // Adding more products from the Zalando store (examples from the URL you provided)
    {
      id: 6,
      name: "Nike Tech Fleece Hoodie",
      price: 119.99,
      image: "https://thumblr.uniid.it/product/338796/cf839c52b56e.jpg?width=1080&format=webp&q=75",
      type: "clothing",
      description: "Premium tech fleece hoodie with excellent warmth and style.",
      company: "Nike",
      color: "Gray",
      size: "S, M, L",
      link: "",
      category: "men",
      style: "streetwear, athletic"
    },

    
  {
    "id": 51,
    "name": "adidas Sportswear T-shirt with Print",
    "price": 119.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/a3682894e24544698909f9f9be069f5b/af207aa3ca1a40eeb593a996cb0969d0.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "A stylish black t-shirt with a multicolor print. Made from 100% jersey cotton. Regular fit with a round neckline and short sleeves.",
    "company": "adidas",
    "color": "Black, Multicolor",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/adidas-sportswear-t-shirt-z-nadrukiem-blackmulticolor-zzo30rg11-q00.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 52,
    "name": "Nike Sportswear Air Force 1 Next Nature Sneakers",
    "price": 449.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/498801266acd4c3ab7962151288656d0/3ab56eb5700a4484ae83ee0fcb41bc99.jpg?imwidth=762&filter=packshot",
    "type": "shoes",
    "description": "Modern Air Force 1 sneakers in white and grey, made from high-quality materials. Comfortable and durable for everyday use.",
    "company": "Nike",
    "color": "White, Grey",
    "size": "40, 41, 42, 43, 44, 45",
    "link": "https://www.zalando.pl/nike-sportswear-air-force-1-next-nature-sneakersy-niskie-whitevast-grey-ni111a192-a19.html",
    "category": "unisex",
    "style": "sportswear, streetwear"
  },
  {
    "id": 53,
    "name": "Converse Chuck Taylor All Star Lift Sneakers",
    "price": 329.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/e1082152949135399ad776697354e2bf/2006bc82168d404e8d52ed1b908e6b5b.jpg?imwidth=762",
    "type": "shoes",
    "description": "High-top Converse Chuck Taylor sneakers in white with black details. A classic design, perfect for casual streetwear.",
    "company": "Converse",
    "color": "White, Black",
    "size": "36, 37, 38, 39, 40, 41",
    "link": "https://www.zalando.pl/converse-chuck-taylor-all-star-lift-sneakersy-wysokie-whiteblack-co411a0u7-a11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 54,
    "name": "adidas Originals Tee Berlin Unisex T-shirt with Print",
    "price": 99.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/1fa8b204216c4e20b5ccd5ed396b8997/a3401ccf0c424607aed3d730f714c418.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "A green graphic t-shirt with the 'Berlin' print. Made of soft cotton for comfort and durability.",
    "company": "adidas Originals",
    "color": "Green",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/adidas-originals-tee-berlin-unisex-t-shirt-z-nadrukiem-collegiate-green-ad12100gs-m11.html",
    "category": "unisex",
    "style": "casual, streetwear"
  },
  {
    "id": 55,
    "name": "Converse Chuck Taylor All Star Lift Sneakers",
    "price": 299.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/92554a4dedfe31a09d1f5e626c5850f6/d7fb787ddfb64a8d8f81a80c45629bca.jpg?imwidth=762",
    "type": "shoes",
    "description": "High-top Chuck Taylor sneakers in white, garnet, and navy. A timeless and versatile design.",
    "company": "Converse",
    "color": "White, Garnet, Navy",
    "size": "36, 37, 38, 39, 40, 41",
    "link": "https://www.zalando.pl/converse-chuck-taylor-all-star-lift-tenisowki-i-trampki-whitegarnetnavy-co411a0nl-a11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 56,
    "name": "adidas Originals Graphic Cali T-shirt with Print",
    "price": 89.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/5ac6f3cb662f4927be9c80b319636d57/0c88ecbc930b4a7b985a150a345f32c2.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "A stylish graphic t-shirt with a bold print. Comfortable and casual, perfect for everyday wear.",
    "company": "adidas Originals",
    "color": "Off White/Night Indigo",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/adidas-originals-graphic-cali-t-t-shirt-z-nadrukiem-off-whitenight-indigo-ad121d1wc-a11.html",
    "category": "women",
    "style": "casual, streetwear"
  },

  {
    "id": 57,
    "name": "Jordan Sports T-shirt",
    "price": 129.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/2b73d2332bcd453e896ea3d92a826ec8/23fdef7581494f93b781d6b82222b113.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "Black sports t-shirt featuring the iconic Jordan logo. Made from breathable fabric for optimal comfort during workouts.",
    "company": "Jordan",
    "color": "Black",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/jordan-koszulka-sportowa-black-joc42d089-q11.html",
    "category": "men",
    "style": "athletic, streetwear"
  },
  {
    "id": 58,
    "name": "Jordan Crossover Hoodie",
    "price": 249.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/ce6ae94a32c64c2dbb42fdb805bbea25/7f94be29a1594ef6bd837f9d3ac72f5c.jpg?imwidth=1800",
    "type": "hoodie",
    "description": "Grey heather hoodie with white Jordan branding. Features a comfortable fit and a front kangaroo pocket.",
    "company": "Jordan",
    "color": "Grey Heather, White",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/jordan-crossover-bluza-z-kapturem-grey-heather-white-joc42g03y-c11.html",
    "category": "men",
    "style": "casual, streetwear"
  },
  {
    "id": 59,
    "name": "Dickies Pizza Print T-shirt",
    "price": 99.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/4bb8c73a4da248d388873544b4e6b486/2f8d58b3a26e416f95df882d4069d846.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "White t-shirt featuring a fun pizza graphic print. Made from 100% cotton for all-day comfort.",
    "company": "Dickies",
    "color": "White",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/dickies-pizza-t-shirt-z-nadrukiem-white-di622o09v-a11.html",
    "category": "unisex",
    "style": "casual, streetwear"
  },
  {
    "id": 60,
    "name": "Nike Sportswear Club Tee",
    "price": 89.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/07cb96e265ab457bbeb3e1b60f1bb33e/f6c3757bf3fb47708fe4c4fc7cc911b3.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "Parachute beige basic t-shirt from Nike's Sportswear Club collection. Soft fabric with a classic fit.",
    "company": "Nike",
    "color": "Beige",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/nike-sportswear-club-tee-t-shirt-basic-parachute-beige-ni122o0ce-b17.html",
    "category": "men",
    "style": "casual, streetwear"
  },
  {
    "id": 61,
    "name": "adidas Originals Oversize T-shirt",
    "price": 109.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/f38e6b86bcd2439693ea07edbf523698/b548b6e3bd174dfba5eb6c5dd643ba09.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "White oversized t-shirt with adidas Originals branding. Designed for a relaxed fit and everyday wear.",
    "company": "adidas Originals",
    "color": "White",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/adidas-originals-oversize-t-shirt-z-nadrukiem-white-ad122o12t-a11.html",
    "category": "unisex",
    "style": "casual, streetwear"
  },
  {
    "id": 62,
    "name": "Jordan Jumpman Sustainable Graphic T-shirt",
    "price": 139.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/c83410ca483543e6a60d66448c9b1640/7736a6e1fba040d1b45e43ff3c9ec3b0.jpg?imwidth=1800",
    "type": "t-shirt",
    "description": "Black t-shirt featuring a sustainable graphic design with the Jumpman logo. Made with eco-friendly materials.",
    "company": "Jordan",
    "color": "Black",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/jordan-jumpman-sustainable-graphic-t-shirt-z-nadrukiem-black-joc43d0a6-q11.html",
    "category": "men",
    "style": "athletic, streetwear"
  },
  {
    "id": 63,
    "name": "Nike Sportswear Air Boxy T-shirt",
    "price": 99.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/c0f61b207fbe46ccb9e6e30b0e6189b2/539f961a6c51494fa005c59b4f382016.jpg?imwidth=762&filter=packshot",
    "type": "t-shirt",
    "description": "Black boxy t-shirt from Nike Sportswear with 'Air' branding. Features a relaxed fit and soft fabric.",
    "company": "Nike",
    "color": "Black",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/nike-sportswear-air-boxy-t-shirt-z-nadrukiem-black-ni124g05t-q11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 64,
    "name": "Nike Sportswear Be Mine Unisex T-shirt",
    "price": 109.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/4e234432d19b4f6a9506a7a4d1a2f2b4/313ed25b0e14425eb84bbe60582d5cfb.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "Black unisex t-shirt with 'Be Mine' print from Nike Sportswear. Made from soft cotton for comfort.",
    "company": "Nike",
    "color": "Black",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/nike-sportswear-tee-be-mine-unisex-t-shirt-z-nadrukiem-black-ni126g0ds-q11.html",
    "category": "unisex",
    "style": "casual, streetwear"
  },
  {
    "id": 65,
    "name": "adidas Originals Sandwich Boyfriend Crew Sweatshirt",
    "price": 229.00,
    "imgage": "https://img01.ztat.net/article/spp-media-p1/ada61db912c14a68ac845c8cdb7fadb3/dfdf99ae886e40a8b3c33057962c05e2.jpg?imwidth=762",
    "type": "sweatshirt",
    "description": "Legend ink sweatshirt with a relaxed boyfriend fit. Features adidas Originals branding and ribbed cuffs.",
    "company": "adidas Originals",
    "color": "Legend Ink",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/adidas-originals-sandwich-boyfriend-crew-bluza-legend-ink-ad126k05o-k11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 66,
    "name": "Karl Kani Black Hoodie",
    "price": 199.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/0586d62cfc074e6ebcb37f1d9d664e7f/55de87be981c4993a68ba4064d500f7c.jpg?imwidth=762&filter=packshot",
    "type": "hoodie",
    "description": "Classic black hoodie from Karl Kani featuring the brand's logo. Made from soft fabric for everyday wear.",
    "company": "Karl Kani",
    "color": "Black",
    "size": "S, M, L, XL",
    "link": "https://www.zalando.pl/karl-kani-bluza-black-kk126k000-q11.html",
    "category": "unisex",
    "style": "casual, streetwear"
  },

  
  {
    "id": 67,
    "name": "Tommy Hilfiger Basic T-Shirt",
    "price": 259.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/342ab96837b1481d86b934c70b97d7b0/4e4c762c365c4f9982506bc1e09c5bd6.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "Classic jersey T-shirt in 'hot coco' color with a regular fit and round neckline.",
    "company": "Tommy Hilfiger",
    "color": "Hot Coco",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/tommy-hilfiger-t-shirt-basic-hot-coco-to121d1bq-o11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 68,
    "name": "Tommy Hilfiger Tonal Flag Regular Tee",
    "price": 219.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/4be5295ff67849b49876ab3daf81baa8/0d1d457b8865403f98b264ed36165156.jpg?imwidth=762",
    "type": "t-shirt",
    "description": "Regular fit T-shirt in 'hickory' color made from 100% cotton jersey.",
    "company": "Tommy Hilfiger",
    "color": "Hickory",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/tommy-hilfiger-tonal-flag-reg-tee-t-shirt-basic-hickory-to121d1av-o11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 69,
    "name": "Tommy Hilfiger Stripe Pull-On Shorts",
    "price": 299.00,
    "image": "ticle/spp-media-p1/TO/12/1S/07/2A/11/TO121S072-A11@12.jpg",
    "type": "shorts",
    "description": "Comfortable pull-on shorts in cloudy blue/ecru with a striped pattern.",
    "company": "Tommy Hilfiger",
    "color": "Cloudy Blue/Ecru",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/tommy-hilfiger-stripe-pull-on-szorty-cloudy-blueecru-to121s072-a11.html",
    "category": "women",
    "style": "casual, summer"
  },
  {
    "id": 70,
    "name": "Tommy Hilfiger Vulc Low-Top Sneakers",
    "price": 399.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/a38444072d984d768aff839db0afa34e/34d15d9dc388429d9e77effc8485371c.jpg?imwidth=762&filter=packshot",
    "type": "shoes",
    "description": "Ecru-colored low-top sneakers with a vulcanized sole for everyday wear.",
    "company": "Tommy Hilfiger",
    "color": "Ecru",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/tommy-hilfiger-vulc-sneakersy-niskie-ecru-to111a1b0-a11.html",
    "category": "women",
    "style": "casual, streetwear"
  },
  {
    "id": 71,
    "name": "Tommy Hilfiger Soft Classic Shirt",
    "price": 349.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/a15de6937aac49f39fd459728a5a7c32/34757475386748949b381b3fc1ad6720.jpg?imwidth=762",
    "type": "shirt",
    "description": "Classic fit shirt in Ithaca dark night navy, perfect for formal occasions.",
    "company": "Tommy Hilfiger",
    "color": "Dark Night Navy",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/tommy-hilfiger-soft-shirt-koszula-classic-ithacadark-night-navy-to121e17a-k11.html",
    "category": "men",
    "style": "formal, business"
  },
  {
    "id": 72,
    "name": "Air Jordan 1 Low Sneakers",
    "price": 519.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/86452f7d4fe149d0baaf1971252be29e/2d1f9603a3b344bf8b3250447a1709b8.jpg?imwidth=762&filter=packshot",
    "type": "shoes",
    "description": "Low-top sneakers in white/ironstone/light soft pink/platinum violet/light armory blue.",
    "company": "Jordan",
    "color": "White, Ironstone/Light Soft Pink/Platinum Violet/Light Armory Blue",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/jordan-air-jordan-1-sneakersy-niskie-whiteironstonelight-soft-pinkplatinum-violetlight-armory-blue-joc11a0am-a11.html",
    "category": "unisex",
    "style": "athletic, streetwear"
  },
  {
    "id": 73,
    "name": "Karl Lagerfeld Printed T-Shirt",
    "price": 299.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/fbd23b1960e6443ba5b79410c76e0b63/36172315e6ce4d808a758d56e320af37.jpg?imwidth=1800",
    "type": "t-shirt",
    "description": "Black T-shirt featuring a distinctive print, offering a modern look.",
    "company": "Karl Lagerfeld",
    "color": "Black",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/karl-lagerfeld-t-shirt-z-nadrukiem-black-k4821d0jn-q11.html",
    "category": "women",
    "style": "designer, casual"
  },
  {
    "id": 74,
    "name": "Karl Lagerfeld Printed T-Shirt",
    "price": 299.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/370cb7f29911495ca9268e3352ed89fb/76c1ba7575a548e38f5828e1b6c5ed48.jpg?imwidth=1800",
    "type": "t-shirt",
    "description": "Light grey melange T-shirt with a stylish print, perfect for casual wear.",
    "company": "Karl Lagerfeld",
    "color": "Grey",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/karl-lagerfeld-t-shirt-z-nadrukiem-light-grey-mel-k4821d0jr-c11.html",
    "category": "women",
    "style": "designer, casual"
  },
  {
    "id": 75,
    "name": "Tommy Hilfiger Outline Flag Script Hoodie",
    "price": 499.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/57cdbcad5abc4c4a80ac2f161015e52d/7aceebc966eb464d8e51cbffab7fb21f.jpg?imwidth=1800",
    "type": "hoodie",
    "description": "Unisex black hoodie featuring the Tommy Hilfiger outline flag script design.",
    "company": "Tommy Hilfiger",
    "color": "Black",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/tommy-hilfiger-outline-flag-script-hoodie-unisex-bluza-z-kapturem-black-to1210050-q11.html",
    "category": "unisex",
    "style": "casual, streetwear"
  },
  {
    "id": 76,
    "name": "BOSS Paddy Polo Shirt",
    "price": 349.00,
    "image": "https://img01.ztat.net/article/spp-media-p1/dfb71e8086a8476fb679d12cfb8acfae/7e914171d60e47ba901893dc21be1770.jpg?imwidth=762",
    "type": "polo",
    "description": "Charcoal-colored polo shirt with a classic fit, suitable for business casual settings.",
    "company": "BOSS",
    "color": "Charcoal",
    "size": "Various Sizes",
    "link": "https://www.zalando.pl/boss-paddy-koszulka-polo-charcoal-bb122p0gn-c15.html",
    "category": "men",
    "style": "business, casual"
  }
]

  
};
  
  export default productsDATA;
  